trigger:
  - main  # Run the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM in Azure Pipelines

variables:
  TF_VERSION: '1.6.0'  # Terraform version
  AZURE_SUBSCRIPTION: '68013f73-ff8b-4a58-a1c4-67fb285c8c95'  # Azure subscription ID

stages:
  - stage: Terraform_Deploy
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: 'ubuntu-latest'  # Define agent inside the job
        steps:

          # Step 1: Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(TF_VERSION)

          # Step 2: Authenticate with Azure using Service Connection
          - task: AzureCLI@2
            displayName: "Login to Azure"
            inputs:
              azureSubscription: 'azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account show

          # Step 3: Initialize Terraform Backend (Azure Storage)
          - script: |
              terraform init \
                -backend-config="resource_group_name=terraform-backend-rg" \
                -backend-config="storage_account_name=mytfstatestoragejq0714" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=terraform.tfstate"
            displayName: "Terraform Init"

          # Step 4: Terraform Plan
          - script: |
              terraform plan -out=tfplan
            displayName: "Terraform Plan"

      # Separate Server Job for Manual Validation
      - job: Manual_Approval
        displayName: "Approve Terraform Apply"
        dependsOn: Terraform  # Ensure this runs after Terraform job
        pool: server  # Run on a server job (NOT an agent)
        steps:
          - task: ManualValidation@1
            displayName: "Approve Terraform Apply"
            inputs:
              notifyUsers: "jlsryn.quiambao@gmail.com"
              instructions: "Review Terraform plan before applying."

      # Terraform Apply job (runs after approval)
      - job: Terraform_Apply
        displayName: "Terraform Apply"
        dependsOn: Manual_Approval  # Wait for manual approval first
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"

