trigger:
  - main  # Run the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu VM in Azure Pipelines

variables:
  TF_VERSION: '1.6.0'  # Terraform version
  AZURE_SUBSCRIPTION: '68013f73-ff8b-4a58-a1c4-67fb285c8c95'  # Azure subscription ID

stages:
  - stage: Terraform_Deploy
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Run Terraform"
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          # Step 0: Verify Terraform Files Exist
          - script: |
              echo "Checking directory structure..."
              ls -R
            displayName: "List all files in the repository"

          # Step 1: Verify Terraform Files Exist
          - script: |
              echo "Checking for Terraform files..."
              ls -la
            displayName: "List files in working directory"

          # Step 2: Install Terraform
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(TF_VERSION)

          # Step 3: Authenticate with Azure using Service Connection
          - task: AzureCLI@2
            displayName: "Login to Azure"
            inputs:
              azureSubscription: 'azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account show

          # Step 4: Initialize Terraform Backend (Azure Storage)
          - script: |
              terraform init \
                -backend-config="resource_group_name=terraform-backend-rg" \
                -backend-config="storage_account_name=mytfstatestoragejq0714" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=terraform.tfstate"
            displayName: "Terraform Init"
            workingDirectory: 'infra/terraform'

          # Step 5: Terraform Plan and Verify tfplan
          - script: |
              echo "Running Terraform Plan..."
              terraform plan -out=tfplan
              echo "Checking if tfplan exists..."
              ls -lah
              if [ ! -f "tfplan" ]; then
                echo "Error: tfplan was not created!"
                exit 1
              fi
            displayName: "Terraform Plan & Verify tfplan"
            workingDirectory: 'infra/terraform'

          # Step 6: Upload tfplan as Artifact (Ensures availability in next job)
          - task: PublishPipelineArtifact@1
            displayName: "Upload tfplan"
            inputs:
              targetPath: 'infra/terraform/tfplan'
              artifact: 'tfplan'

      # Separate Server Job for Manual Validation
      - job: Manual_Approval
        displayName: "Approve Terraform Apply"
        dependsOn: Terraform
        pool: server  # Run on a server job (NOT an agent)
        steps:
          - task: ManualValidation@1
            displayName: "Approve Terraform Apply"
            inputs:
              notifyUsers: "jlsryn.quiambao@gmail.com"
              instructions: "Review Terraform plan before applying."

      # Terraform Apply job (runs after approval)
      - job: Terraform_Apply
        displayName: "Terraform Apply"
        dependsOn: Manual_Approval
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          # Step 7: Download tfplan Artifact
          - task: DownloadPipelineArtifact@2
            displayName: "Download tfplan"
            inputs:
              artifact: 'tfplan'
              path: 'infra/terraform'

          # Step 8: Verify tfplan Before Apply
          - script: |
              echo "Verifying tfplan before apply..."
              ls -lah
              if [ ! -f "tfplan" ]; then
                echo "Error: tfplan is missing in Terraform Apply step!"
                exit 1
              fi
            displayName: "Check tfplan Before Apply"
            workingDirectory: 'infra/terraform'

          # Step 9: Apply Terraform Changes
          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            workingDirectory: 'infra/terraform'

